import 'package:flutter/material.dart';

/// Collection of Material Icons for routine items
class RoutineIcons {
  RoutineIcons._();

  static final List<Map<String, dynamic>> allIcons = [
    // Health & Fitness
    {'icon': Icons.water_drop, 'name': 'water'},
    {'icon': Icons.local_drink, 'name': 'drink'},
    {'icon': Icons.water_drop_outlined, 'name': 'hydrate'},
    {'icon': Icons.fitness_center, 'name': 'fitness'},
    {'icon': Icons.self_improvement, 'name': 'meditation'},
    {'icon': Icons.spa, 'name': 'spa'},
    {'icon': Icons.accessibility_new, 'name': 'yoga'},
    {'icon': Icons.directions_run, 'name': 'run'},
    {'icon': Icons.directions_walk, 'name': 'walk'},
    {'icon': Icons.hiking, 'name': 'hiking'},
    {'icon': Icons.pool, 'name': 'swim'},
    {'icon': Icons.sports_basketball, 'name': 'basketball'},
    {'icon': Icons.sports_soccer, 'name': 'soccer'},
    {'icon': Icons.sports_tennis, 'name': 'tennis'},
    {'icon': Icons.sports_volleyball, 'name': 'volleyball'},
    {'icon': Icons.sports_baseball, 'name': 'baseball'},
    {'icon': Icons.sports_football, 'name': 'football'},
    {'icon': Icons.sports_golf, 'name': 'golf'},
    {'icon': Icons.sports_handball, 'name': 'handball'},
    {'icon': Icons.sports_hockey, 'name': 'hockey'},
    {'icon': Icons.sports_mma, 'name': 'mma'},
    {'icon': Icons.sports_martial_arts, 'name': 'martial arts'},
    {'icon': Icons.sports_gymnastics, 'name': 'gymnastics'},
    {'icon': Icons.sports_esports, 'name': 'gaming'},
    {'icon': Icons.skateboarding, 'name': 'skateboard'},
    {'icon': Icons.snowboarding, 'name': 'snowboard'},
    {'icon': Icons.surfing, 'name': 'surf'},
    {'icon': Icons.kayaking, 'name': 'kayak'},
    {'icon': Icons.sailing, 'name': 'sailing'},
    {'icon': Icons.scuba_diving, 'name': 'diving'},
    {'icon': Icons.downhill_skiing, 'name': 'skiing'},
    {'icon': Icons.paragliding, 'name': 'paragliding'},
    {'icon': Icons.sledding, 'name': 'sledding'},
    {'icon': Icons.ice_skating, 'name': 'skating'},
    
    // Food & Drink
    {'icon': Icons.local_cafe, 'name': 'coffee'},
    {'icon': Icons.coffee, 'name': 'espresso'},
    {'icon': Icons.emoji_food_beverage, 'name': 'tea'},
    {'icon': Icons.restaurant, 'name': 'food'},
    {'icon': Icons.restaurant_menu, 'name': 'menu'},
    {'icon': Icons.fastfood, 'name': 'fast food'},
    {'icon': Icons.lunch_dining, 'name': 'lunch'},
    {'icon': Icons.dinner_dining, 'name': 'dinner'},
    {'icon': Icons.breakfast_dining, 'name': 'breakfast'},
    {'icon': Icons.brunch_dining, 'name': 'brunch'},
    {'icon': Icons.ramen_dining, 'name': 'ramen'},
    {'icon': Icons.cake, 'name': 'cake'},
    {'icon': Icons.local_pizza, 'name': 'pizza'},
    {'icon': Icons.local_bar, 'name': 'bar'},
    {'icon': Icons.liquor, 'name': 'liquor'},
    {'icon': Icons.tapas, 'name': 'tapas'},
    {'icon': Icons.set_meal, 'name': 'meal'},
    {'icon': Icons.icecream, 'name': 'icecream'},
    {'icon': Icons.cookie, 'name': 'cookie'},
    
    // Sleep & Rest
    {'icon': Icons.nights_stay, 'name': 'sleep'},
    {'icon': Icons.nightlight, 'name': 'night'},
    {'icon': Icons.bed, 'name': 'bed'},
    {'icon': Icons.bedtime, 'name': 'bedtime'},
    {'icon': Icons.king_bed, 'name': 'rest'},
    {'icon': Icons.single_bed, 'name': 'nap'},
    {'icon': Icons.crib, 'name': 'crib'},
    {'icon': Icons.dark_mode, 'name': 'dark'},
    
    // Work & Study
    {'icon': Icons.work, 'name': 'work'},
    {'icon': Icons.work_outline, 'name': 'office'},
    {'icon': Icons.business_center, 'name': 'business'},
    {'icon': Icons.business, 'name': 'company'},
    {'icon': Icons.laptop, 'name': 'laptop'},
    {'icon': Icons.computer, 'name': 'computer'},
    {'icon': Icons.desktop_windows, 'name': 'desktop'},
    {'icon': Icons.book, 'name': 'book'},
    {'icon': Icons.menu_book, 'name': 'read'},
    {'icon': Icons.auto_stories, 'name': 'stories'},
    {'icon': Icons.import_contacts, 'name': 'study'},
    {'icon': Icons.school, 'name': 'school'},
    {'icon': Icons.library_books, 'name': 'library'},
    {'icon': Icons.edit_note, 'name': 'notes'},
    {'icon': Icons.note, 'name': 'note'},
    {'icon': Icons.task, 'name': 'task'},
    {'icon': Icons.assignment, 'name': 'assignment'},
    {'icon': Icons.description, 'name': 'document'},
    
    // Time & Planning
    {'icon': Icons.timer, 'name': 'timer'},
    {'icon': Icons.timer_outlined, 'name': 'stopwatch'},
    {'icon': Icons.alarm, 'name': 'alarm'},
    {'icon': Icons.alarm_on, 'name': 'alarm on'},
    {'icon': Icons.alarm_add, 'name': 'set alarm'},
    {'icon': Icons.access_time, 'name': 'time'},
    {'icon': Icons.schedule, 'name': 'schedule'},
    {'icon': Icons.watch_later, 'name': 'later'},
    {'icon': Icons.calendar_today, 'name': 'calendar'},
    {'icon': Icons.event, 'name': 'event'},
    {'icon': Icons.event_note, 'name': 'event note'},
    {'icon': Icons.today, 'name': 'today'},
    {'icon': Icons.date_range, 'name': 'date'},
    
    // Shopping & Errands
    {'icon': Icons.shopping_cart, 'name': 'shopping'},
    {'icon': Icons.shopping_bag, 'name': 'bag'},
    {'icon': Icons.shopping_basket, 'name': 'basket'},
    {'icon': Icons.add_shopping_cart, 'name': 'add cart'},
    {'icon': Icons.storefront, 'name': 'store'},
    {'icon': Icons.store, 'name': 'shop'},
    {'icon': Icons.local_mall, 'name': 'mall'},
    {'icon': Icons.local_grocery_store, 'name': 'grocery'},
    {'icon': Icons.local_shipping, 'name': 'shipping'},
    {'icon': Icons.delivery_dining, 'name': 'delivery'},
    {'icon': Icons.backpack, 'name': 'backpack'},
    {'icon': Icons.luggage, 'name': 'luggage'},
    
    // Home & Cleaning
    {'icon': Icons.home, 'name': 'home'},
    {'icon': Icons.house, 'name': 'house'},
    {'icon': Icons.cottage, 'name': 'cottage'},
    {'icon': Icons.apartment, 'name': 'apartment'},
    {'icon': Icons.cleaning_services, 'name': 'cleaning'},
    {'icon': Icons.clean_hands, 'name': 'clean'},
    {'icon': Icons.checkroom, 'name': 'clothes'},
    {'icon': Icons.dry_cleaning, 'name': 'dry clean'},
    {'icon': Icons.local_laundry_service, 'name': 'laundry'},
    {'icon': Icons.bathtub, 'name': 'bath'},
    {'icon': Icons.shower, 'name': 'shower'},
    {'icon': Icons.soap, 'name': 'soap'},
    {'icon': Icons.wash, 'name': 'wash'},
    {'icon': Icons.countertops, 'name': 'countertop'},
    {'icon': Icons.kitchen, 'name': 'kitchen'},
    {'icon': Icons.microwave, 'name': 'microwave'},
    {'icon': Icons.blender, 'name': 'blender'},
    
    // Health & Medicine
    {'icon': Icons.local_hospital, 'name': 'hospital'},
    {'icon': Icons.medical_services, 'name': 'medical'},
    {'icon': Icons.medication, 'name': 'medication'},
    {'icon': Icons.vaccines, 'name': 'vaccine'},
    {'icon': Icons.local_pharmacy, 'name': 'pharmacy'},
    {'icon': Icons.health_and_safety, 'name': 'health'},
    {'icon': Icons.healing, 'name': 'healing'},
    {'icon': Icons.monitor_heart, 'name': 'heart rate'},
    {'icon': Icons.favorite, 'name': 'heart'},
    {'icon': Icons.favorite_border, 'name': 'like'},
    {'icon': Icons.volunteer_activism, 'name': 'care'},
    
    // Entertainment & Hobbies
    {'icon': Icons.music_note, 'name': 'music'},
    {'icon': Icons.piano, 'name': 'piano'},
    {'icon': Icons.music_video, 'name': 'guitar'},
    {'icon': Icons.headphones, 'name': 'headphones'},
    {'icon': Icons.speaker, 'name': 'speaker'},
    {'icon': Icons.mic, 'name': 'microphone'},
    {'icon': Icons.movie, 'name': 'movie'},
    {'icon': Icons.theaters, 'name': 'theater'},
    {'icon': Icons.tv, 'name': 'tv'},
    {'icon': Icons.videocam, 'name': 'video'},
    {'icon': Icons.camera, 'name': 'camera'},
    {'icon': Icons.photo_camera, 'name': 'photo'},
    {'icon': Icons.brush, 'name': 'art'},
    {'icon': Icons.palette, 'name': 'palette'},
    {'icon': Icons.draw, 'name': 'draw'},
    {'icon': Icons.color_lens, 'name': 'color'},
    {'icon': Icons.casino, 'name': 'dice'},
    {'icon': Icons.games, 'name': 'games'},
    
    // Communication & Social
    {'icon': Icons.phone, 'name': 'phone'},
    {'icon': Icons.call, 'name': 'call'},
    {'icon': Icons.message, 'name': 'message'},
    {'icon': Icons.chat, 'name': 'chat'},
    {'icon': Icons.email, 'name': 'email'},
    {'icon': Icons.mail, 'name': 'mail'},
    {'icon': Icons.forum, 'name': 'forum'},
    {'icon': Icons.groups, 'name': 'group'},
    {'icon': Icons.people, 'name': 'people'},
    {'icon': Icons.person, 'name': 'person'},
    {'icon': Icons.face, 'name': 'face'},
    {'icon': Icons.emoji_emotions, 'name': 'emotion'},
    {'icon': Icons.mood, 'name': 'mood'},
    {'icon': Icons.sentiment_satisfied, 'name': 'happy'},
    
    // Transportation
    {'icon': Icons.directions_car, 'name': 'car'},
    {'icon': Icons.directions_bike, 'name': 'bike'},
    {'icon': Icons.two_wheeler, 'name': 'motorcycle'},
    {'icon': Icons.train, 'name': 'train'},
    {'icon': Icons.subway, 'name': 'subway'},
    {'icon': Icons.tram, 'name': 'tram'},
    {'icon': Icons.directions_bus, 'name': 'bus'},
    {'icon': Icons.flight, 'name': 'flight'},
    {'icon': Icons.airport_shuttle, 'name': 'shuttle'},
    {'icon': Icons.local_taxi, 'name': 'taxi'},
    {'icon': Icons.electric_car, 'name': 'electric'},
    {'icon': Icons.electric_bike, 'name': 'e-bike'},
    {'icon': Icons.electric_scooter, 'name': 'scooter'},
    {'icon': Icons.pedal_bike, 'name': 'pedal'},
    
    // Nature & Weather
    {'icon': Icons.wb_sunny, 'name': 'sun'},
    {'icon': Icons.wb_cloudy, 'name': 'cloud'},
    {'icon': Icons.wb_twilight, 'name': 'sunset'},
    {'icon': Icons.light_mode, 'name': 'light'},
    {'icon': Icons.brightness_high, 'name': 'bright'},
    {'icon': Icons.yard, 'name': 'garden'},
    {'icon': Icons.park, 'name': 'park'},
    {'icon': Icons.forest, 'name': 'forest'},
    {'icon': Icons.nature, 'name': 'nature'},
    {'icon': Icons.nature_people, 'name': 'outdoor'},
    {'icon': Icons.grass, 'name': 'grass'},
    {'icon': Icons.eco, 'name': 'eco'},
    {'icon': Icons.energy_savings_leaf, 'name': 'leaf'},
    {'icon': Icons.local_florist, 'name': 'flower'},
    {'icon': Icons.beach_access, 'name': 'beach'},
    {'icon': Icons.waves, 'name': 'waves'},
    {'icon': Icons.water, 'name': 'water drop'},
    {'icon': Icons.air, 'name': 'air'},
    {'icon': Icons.bolt, 'name': 'bolt'},
    {'icon': Icons.flash_on, 'name': 'flash'},
    
    // Pets & Animals
    {'icon': Icons.pets, 'name': 'pet'},
    {'icon': Icons.cruelty_free, 'name': 'animal'},
    
    // Technology & Devices
    {'icon': Icons.smartphone, 'name': 'smartphone'},
    {'icon': Icons.tablet, 'name': 'tablet'},
    {'icon': Icons.watch, 'name': 'watch'},
    {'icon': Icons.devices, 'name': 'devices'},
    {'icon': Icons.router, 'name': 'router'},
    {'icon': Icons.wifi, 'name': 'wifi'},
    {'icon': Icons.bluetooth, 'name': 'bluetooth'},
    {'icon': Icons.battery_charging_full, 'name': 'battery'},
    {'icon': Icons.power, 'name': 'power'},
    {'icon': Icons.light, 'name': 'bulb'},
    {'icon': Icons.lightbulb, 'name': 'idea'},
    
    // Miscellaneous
    {'icon': Icons.star, 'name': 'star'},
    {'icon': Icons.star_border, 'name': 'star outline'},
    {'icon': Icons.celebration, 'name': 'party'},
    {'icon': Icons.cake_outlined, 'name': 'birthday'},
    {'icon': Icons.card_giftcard, 'name': 'gift'},
    {'icon': Icons.redeem, 'name': 'reward'},
    {'icon': Icons.emoji_events, 'name': 'trophy'},
    {'icon': Icons.workspace_premium, 'name': 'premium'},
    {'icon': Icons.flag, 'name': 'flag'},
    {'icon': Icons.push_pin, 'name': 'pin'},
    {'icon': Icons.location_on, 'name': 'location'},
    {'icon': Icons.map, 'name': 'map'},
    {'icon': Icons.explore, 'name': 'explore'},
    {'icon': Icons.recycling, 'name': 'recycle'},
    {'icon': Icons.local_fire_department, 'name': 'fire'},
    {'icon': Icons.ac_unit, 'name': 'cold'},
    {'icon': Icons.thermostat, 'name': 'temperature'},
    
    // Morning & Evening Routines
    {'icon': Icons.alarm_add, 'name': 'wake up'},
    {'icon': Icons.snooze, 'name': 'snooze'},
    {'icon': Icons.wc, 'name': 'bathroom'},
    {'icon': Icons.bathroom, 'name': 'washroom'},
    {'icon': Icons.shower_outlined, 'name': 'morning shower'},
    {'icon': Icons.hot_tub, 'name': 'hot tub'},
    {'icon': Icons.waving_hand, 'name': 'greeting'},
    {'icon': Icons.brightness_6, 'name': 'dawn'},
    {'icon': Icons.mode_night, 'name': 'evening'},
    {'icon': Icons.bedtime_outlined, 'name': 'sleep time'},
    {'icon': Icons.hotel, 'name': 'hotel'},
    {'icon': Icons.airline_seat_flat, 'name': 'lie down'},
    
    // Personal Care & Beauty
    {'icon': Icons.face_retouching_natural, 'name': 'skincare'},
    {'icon': Icons.brush_outlined, 'name': 'makeup'},
    {'icon': Icons.content_cut, 'name': 'haircut'},
    {'icon': Icons.cut, 'name': 'trim'},
    {'icon': Icons.pregnant_woman, 'name': 'maternity'},
    {'icon': Icons.child_care, 'name': 'baby care'},
    {'icon': Icons.child_friendly, 'name': 'kids'},
    {'icon': Icons.family_restroom, 'name': 'family'},
    {'icon': Icons.accessible, 'name': 'accessibility'},
    {'icon': Icons.elderly, 'name': 'elderly'},
    
    // Food Preparation
    {'icon': Icons.soup_kitchen, 'name': 'cooking'},
    {'icon': Icons.outdoor_grill, 'name': 'grill'},
    {'icon': Icons.rice_bowl, 'name': 'rice'},
    {'icon': Icons.egg, 'name': 'egg'},
    {'icon': Icons.egg_alt, 'name': 'breakfast egg'},
    {'icon': Icons.food_bank, 'name': 'groceries'},
    {'icon': Icons.takeout_dining, 'name': 'takeout'},
    {'icon': Icons.room_service, 'name': 'room service'},
    {'icon': Icons.bakery_dining, 'name': 'bakery'},
    {'icon': Icons.no_food, 'name': 'fasting'},
    {'icon': Icons.restaurant_outlined, 'name': 'dine out'},
    
    // Health & Wellness Extended
    {'icon': Icons.psychology, 'name': 'mental health'},
    {'icon': Icons.psychology_alt, 'name': 'therapy'},
    {'icon': Icons.emergency, 'name': 'emergency'},
    {'icon': Icons.bloodtype, 'name': 'blood'},
    {'icon': Icons.masks, 'name': 'mask'},
    {'icon': Icons.sanitizer, 'name': 'sanitizer'},
    {'icon': Icons.sick, 'name': 'sick'},
    {'icon': Icons.coronavirus, 'name': 'virus'},
    {'icon': Icons.medical_information, 'name': 'medical info'},
    {'icon': Icons.science, 'name': 'science'},
    {'icon': Icons.biotech, 'name': 'biotech'},
    {'icon': Icons.medication_liquid, 'name': 'vitamin'},
    
    // Productivity & Focus
    {'icon': Icons.checklist, 'name': 'checklist'},
    {'icon': Icons.check_circle, 'name': 'complete'},
    {'icon': Icons.check_circle_outline, 'name': 'todo'},
    {'icon': Icons.radio_button_unchecked, 'name': 'unchecked'},
    {'icon': Icons.done_all, 'name': 'done all'},
    {'icon': Icons.fact_check, 'name': 'verify'},
    {'icon': Icons.rule, 'name': 'rules'},
    {'icon': Icons.gavel, 'name': 'decision'},
    {'icon': Icons.balance, 'name': 'balance'},
    {'icon': Icons.insights, 'name': 'insights'},
    {'icon': Icons.analytics, 'name': 'analytics'},
    {'icon': Icons.troubleshoot, 'name': 'problem solve'},
    {'icon': Icons.tips_and_updates, 'name': 'tips'},
    {'icon': Icons.celebration_outlined, 'name': 'achieve'},
    
    // Learning & Reading
    {'icon': Icons.history_edu, 'name': 'history'},
    {'icon': Icons.translate, 'name': 'language'},
    {'icon': Icons.quiz, 'name': 'quiz'},
    {'icon': Icons.calculate, 'name': 'calculate'},
    {'icon': Icons.functions, 'name': 'math'},
    {'icon': Icons.architecture, 'name': 'design'},
    {'icon': Icons.engineering, 'name': 'engineering'},
    {'icon': Icons.construction, 'name': 'construction'},
    {'icon': Icons.handyman, 'name': 'handyman'},
    {'icon': Icons.build, 'name': 'build'},
    {'icon': Icons.home_repair_service, 'name': 'repair'},
    
    // Finance & Money
    {'icon': Icons.attach_money, 'name': 'money'},
    {'icon': Icons.euro, 'name': 'euro'},
    {'icon': Icons.currency_pound, 'name': 'pound'},
    {'icon': Icons.currency_yen, 'name': 'yen'},
    {'icon': Icons.currency_bitcoin, 'name': 'bitcoin'},
    {'icon': Icons.savings, 'name': 'savings'},
    {'icon': Icons.account_balance, 'name': 'bank'},
    {'icon': Icons.account_balance_wallet, 'name': 'wallet'},
    {'icon': Icons.credit_card, 'name': 'credit card'},
    {'icon': Icons.payment, 'name': 'payment'},
    {'icon': Icons.receipt, 'name': 'receipt'},
    {'icon': Icons.receipt_long, 'name': 'invoice'},
    {'icon': Icons.request_quote, 'name': 'quote'},
    {'icon': Icons.price_check, 'name': 'price'},
    {'icon': Icons.discount, 'name': 'discount'},
    {'icon': Icons.sell, 'name': 'sell'},
    {'icon': Icons.point_of_sale, 'name': 'pos'},
    
    // Social & Relationships
    {'icon': Icons.favorite_outline, 'name': 'love'},
    {'icon': Icons.volunteer_activism, 'name': 'charity'},
    {'icon': Icons.thumb_up, 'name': 'like'},
    {'icon': Icons.thumb_up_outlined, 'name': 'approve'},
    {'icon': Icons.thumb_down, 'name': 'dislike'},
    {'icon': Icons.handshake, 'name': 'agreement'},
    {'icon': Icons.emoji_people, 'name': 'people'},
    {'icon': Icons.emoji_emotions_outlined, 'name': 'happy'},
    {'icon': Icons.sentiment_very_satisfied, 'name': 'very happy'},
    {'icon': Icons.sentiment_dissatisfied, 'name': 'sad'},
    {'icon': Icons.sentiment_neutral, 'name': 'neutral'},
    {'icon': Icons.self_improvement_outlined, 'name': 'peace'},
    
    // Entertainment Extended
    {'icon': Icons.sports_score, 'name': 'score'},
    {'icon': Icons.sports_kabaddi, 'name': 'kabaddi'},
    {'icon': Icons.sports_cricket, 'name': 'cricket'},
    {'icon': Icons.sports_rugby, 'name': 'rugby'},
    {'icon': Icons.sports_motorsports, 'name': 'motorsports'},
    {'icon': Icons.sports, 'name': 'sports'},
    {'icon': Icons.stadium, 'name': 'stadium'},
    {'icon': Icons.attractions, 'name': 'attractions'},
    {'icon': Icons.nightlife, 'name': 'nightlife'},
    {'icon': Icons.festival, 'name': 'festival'},
    {'icon': Icons.castle, 'name': 'castle'},
    {'icon': Icons.museum, 'name': 'museum'},
    
    // Writing & Creating
    {'icon': Icons.create, 'name': 'create'},
    {'icon': Icons.edit, 'name': 'edit'},
    {'icon': Icons.edit_outlined, 'name': 'write'},
    {'icon': Icons.border_color, 'name': 'pen'},
    {'icon': Icons.design_services, 'name': 'design'},
    {'icon': Icons.format_paint, 'name': 'paint'},
    {'icon': Icons.image, 'name': 'image'},
    {'icon': Icons.photo, 'name': 'photography'},
    {'icon': Icons.photo_library, 'name': 'gallery'},
    {'icon': Icons.collections, 'name': 'collection'},
    {'icon': Icons.auto_awesome, 'name': 'awesome'},
    
    // Time Management
    {'icon': Icons.hourglass_empty, 'name': 'hourglass'},
    {'icon': Icons.hourglass_full, 'name': 'time up'},
    {'icon': Icons.timelapse, 'name': 'timelapse'},
    {'icon': Icons.history, 'name': 'history'},
    {'icon': Icons.update, 'name': 'update'},
    {'icon': Icons.pending, 'name': 'pending'},
    {'icon': Icons.pending_actions, 'name': 'waiting'},
    {'icon': Icons.more_time, 'name': 'more time'},
    {'icon': Icons.running_with_errors, 'name': 'deadline'},
    
    // Weather Extended
    {'icon': Icons.thunderstorm, 'name': 'storm'},
    {'icon': Icons.umbrella, 'name': 'umbrella'},
    {'icon': Icons.sunny, 'name': 'sunny'},
    {'icon': Icons.cloudy_snowing, 'name': 'snow'},
    {'icon': Icons.severe_cold, 'name': 'freezing'},
    {'icon': Icons.foggy, 'name': 'fog'},
    {'icon': Icons.grain, 'name': 'rain'},
    {'icon': Icons.wind_power, 'name': 'wind'},
    
    // Notifications & Alerts
    {'icon': Icons.notifications, 'name': 'notification'},
    {'icon': Icons.notifications_active, 'name': 'alert'},
    {'icon': Icons.notifications_off, 'name': 'mute'},
    {'icon': Icons.notification_important, 'name': 'important'},
    {'icon': Icons.priority_high, 'name': 'priority'},
    {'icon': Icons.report, 'name': 'report'},
    {'icon': Icons.error, 'name': 'error'},
    {'icon': Icons.warning, 'name': 'warning'},
    {'icon': Icons.info, 'name': 'info'},
    {'icon': Icons.help, 'name': 'help'},
    
    // Security & Privacy
    {'icon': Icons.lock, 'name': 'lock'},
    {'icon': Icons.lock_open, 'name': 'unlock'},
    {'icon': Icons.key, 'name': 'key'},
    {'icon': Icons.vpn_key, 'name': 'vpn key'},
    {'icon': Icons.security, 'name': 'security'},
    {'icon': Icons.privacy_tip, 'name': 'privacy'},
    {'icon': Icons.verified, 'name': 'verified'},
    {'icon': Icons.verified_user, 'name': 'verified user'},
    {'icon': Icons.shield, 'name': 'shield'},
    {'icon': Icons.admin_panel_settings, 'name': 'admin'},
    
    // Settings & Controls
    {'icon': Icons.settings, 'name': 'settings'},
    {'icon': Icons.tune, 'name': 'adjust'},
    {'icon': Icons.build_circle, 'name': 'tools'},
    {'icon': Icons.extension, 'name': 'extension'},
    {'icon': Icons.widgets, 'name': 'widgets'},
    {'icon': Icons.dashboard, 'name': 'dashboard'},
    {'icon': Icons.view_module, 'name': 'modules'},
    {'icon': Icons.apps, 'name': 'apps'},
    {'icon': Icons.grid_view, 'name': 'grid'},
    {'icon': Icons.window, 'name': 'window'},
    
    // Favorites & Bookmarks
    {'icon': Icons.bookmark, 'name': 'bookmark'},
    {'icon': Icons.bookmark_border, 'name': 'save'},
    {'icon': Icons.bookmarks, 'name': 'bookmarks'},
    {'icon': Icons.grade, 'name': 'grade'},
    {'icon': Icons.stars, 'name': 'stars'},
    {'icon': Icons.military_tech, 'name': 'medal'},
    {'icon': Icons.new_releases, 'name': 'new'},
    {'icon': Icons.fiber_new, 'name': 'new item'},
    
    // Navigation Extended
    {'icon': Icons.arrow_forward, 'name': 'next'},
    {'icon': Icons.arrow_back, 'name': 'back'},
    {'icon': Icons.arrow_upward, 'name': 'up'},
    {'icon': Icons.arrow_downward, 'name': 'down'},
    {'icon': Icons.north, 'name': 'north'},
    {'icon': Icons.south, 'name': 'south'},
    {'icon': Icons.east, 'name': 'east'},
    {'icon': Icons.west, 'name': 'west'},
    {'icon': Icons.my_location, 'name': 'my location'},
    {'icon': Icons.near_me, 'name': 'near me'},
    {'icon': Icons.navigation, 'name': 'navigation'},
    {'icon': Icons.explore_outlined, 'name': 'compass'},
  ];
}

